/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import NEGOCIO.ConexionBD;
import NEGOCIO.CurpGenerator;
import NEGOCIO.LicenciaManager;
import java.sql.Connection;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 * Clase donde tiene las cosas de licencia desde validar que no esten vacios los
 * campos de texto hasta la funcionalidad de botenoes y la informacion que vamos
 * a manejar. (╹ڡ╹ )
 *
 * @author Jesus Gabriel
 */
public class Licencias extends javax.swing.JFrame {

    LicenciaManager lm = new LicenciaManager();

    //variables para validar los checkbox
    String vigencia = "";
    String discapacidadSeleccionada = "";

    /**
     * Creates new form Licencias
     */
    public Licencias() {
        initComponents();
        ConexionBD conexionBD = new ConexionBD();
        Connection conexion = ConexionBD.obtenerConexion();
        lm = new LicenciaManager();
        lm = new LicenciaManager(conexion);
    }

    // Método para obtener el valor de la vigencia según el checkbox seleccionado
    private int obtenerValorVigencia() {
        int vigencia = 0;
        if (jCheckBox1año.isSelected()) {
            vigencia = 1;
        } else if (jCheckBox2años.isSelected()) {
            vigencia = 2;
        } else if (jCheckBox3años.isSelected()) {
            vigencia = 3;
        }
        return vigencia;

    }

    private String obtenerTipoLicencia() {
        return ComboBoxTipo.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupador = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtAPaterno = new javax.swing.JTextField();
        txtAMaterno = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        lblVigencia = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblRFC = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDiscapacidad = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jCheckBoxNo = new javax.swing.JCheckBox();
        jCheckBoxRenovacion = new javax.swing.JCheckBox();
        jCheckBoxSi = new javax.swing.JCheckBox();
        jCheckBox1año = new javax.swing.JCheckBox();
        jCheckBox2años = new javax.swing.JCheckBox();
        jCheckBox3años = new javax.swing.JCheckBox();
        jCheckBoxPrimeraVez = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        lblNumLicencia = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agrupador.setBackground(new java.awt.Color(244, 244, 244));
        Agrupador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setText("Modulo de Licencias");
        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        Agrupador.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        btnVerificar.setText("Verificar");
        btnVerificar.setBackground(new java.awt.Color(0, 51, 102));
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        Agrupador.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 190, 40));

        btnRegresar.setText("Regresar");
        btnRegresar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        Agrupador.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 230, 50));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel4.setText("Seleccione un tipo de licencia:");
        Agrupador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 240, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel5.setText("Datos del solicitante");
        Agrupador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Agrupador.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 10, 530));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel6.setText("Tipo de tramite:");
        Agrupador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel7.setText("Nombre:");
        Agrupador.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel8.setText("Apellido Paterno:");
        Agrupador.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel9.setText("Apellido Materno:");
        Agrupador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, -1));

        jLabel10.setText("Fecha Nacimiento:");
        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel11.setText("RFC:");
        Agrupador.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, -1));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel12.setText("Telefono:");
        Agrupador.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, -1));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel13.setText("Tipo:");
        Agrupador.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 70, -1));

        jLabel14.setText("Vigencia:");
        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 80, -1));

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovilista", "Motociclista", "Chofer" }));
        ComboBoxTipo.setEnabled(false);
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });
        Agrupador.add(ComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 300, -1));

        jLabel15.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel15.setText("Discapacidad:");
        Agrupador.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, -1));

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        Agrupador.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 290, -1));

        txtTelefono.setEnabled(false);
        Agrupador.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 290, -1));

        txtAPaterno.setEnabled(false);
        Agrupador.add(txtAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 290, -1));

        txtAMaterno.setEnabled(false);
        Agrupador.add(txtAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 290, -1));

        txtRFC.setEnabled(false);
        Agrupador.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, -1));

        lblVigencia.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 120, 20));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel17.setText("Apellido Paterno:");
        Agrupador.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, -1));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel18.setText("Apellido Materno:");
        Agrupador.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 130, -1));

        jLabel19.setText("Fecha Nacimiento:");
        jLabel19.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, -1));

        jLabel20.setText("RFC:");
        jLabel20.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, -1));

        jLabel21.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel21.setText("Telefono:");
        Agrupador.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 150, -1));

        jLabel22.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel22.setText("Discapacidad:");
        Agrupador.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 150, -1));

        lblCosto.setText("$0.0");
        lblCosto.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 100, -1));

        jLabel24.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel24.setText("Tipo:");
        Agrupador.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 70, -1));

        jLabel25.setText("Nombre:");
        jLabel25.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 120, -1));

        lblNombre.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 120, 20));

        lblApellidoPaterno.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, 20));

        lblApellidoMaterno.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 120, 20));

        lblFechaNacimiento.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        Agrupador.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 120, 20));

        lblRFC.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 120, 20));

        lblTelefono.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 120, 20));

        lblDiscapacidad.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 120, 20));

        lblTipo.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 120, 20));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBackground(new java.awt.Color(0, 51, 102));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        Agrupador.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notas (2).png"))); // NOI18N
        Agrupador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 20, 20));

        jLabel3.setText("Una vez haya revisado todo de confirmar\n");
        Agrupador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 240, 30));

        dateNacimiento.setEnabled(false);
        Agrupador.add(dateNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 290, -1));

        jCheckBoxNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxNo.setText("No");
        jCheckBoxNo.setEnabled(false);
        jCheckBoxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNoActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBoxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 50, 30));

        jCheckBoxRenovacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxRenovacion.setText("Renovacion");
        jCheckBoxRenovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRenovacionActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBoxRenovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 120, 30));

        jCheckBoxSi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxSi.setText("SI");
        jCheckBoxSi.setEnabled(false);
        jCheckBoxSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSiActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBoxSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 50, 30));

        jCheckBox1año.setText("1 Año");
        jCheckBox1año.setEnabled(false);
        jCheckBox1año.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1añoActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBox1año, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 80, 30));

        jCheckBox2años.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2años.setText("2 Años");
        jCheckBox2años.setEnabled(false);
        jCheckBox2años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2añosActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBox2años, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 80, 30));

        jCheckBox3años.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox3años.setText("3 Años");
        jCheckBox3años.setEnabled(false);
        jCheckBox3años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3añosActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBox3años, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 80, 30));

        jCheckBoxPrimeraVez.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxPrimeraVez.setText("Primera Vez");
        jCheckBoxPrimeraVez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPrimeraVezActionPerformed(evt);
            }
        });
        Agrupador.add(jCheckBoxPrimeraVez, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, 30));

        jLabel26.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel26.setText("Vigencia:");
        Agrupador.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 80, -1));

        lblNumLicencia.setText("----------------");
        lblNumLicencia.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        Agrupador.add(lblNumLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 140, -1));

        jLabel28.setText("Costo:");
        jLabel28.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        Agrupador.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 80, -1));

        jLabel29.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel29.setText("Numero Licencia:");
        Agrupador.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método que se ejecuta al hacer clic en el botón "Verificar". Pasa la
     * información ingresada a los JLabels para confirmación del usuario antes
     * de enviarla a la base de datos. También calcula y muestra el costo del
     * trámite según la vigencia y la discapacidad seleccionada.
     *
     * @param evt El evento de acción que desencadena este método (clic en el
     * botón "Verificar").
     */
    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // Calcular el costo basado en la vigencia y la discapacidad
        int costo = 0;

        if (jCheckBoxSi.isSelected()) {
            // Obtener la vigencia seleccionada
            if (jCheckBox1año.isSelected()) {
                vigencia = "1 Año";
                costo = 200; // Costo base para 1 año
            } else if (jCheckBox2años.isSelected()) {
                vigencia = "2 Años";
                costo = 500; // Costo base para 2 años
            } else if (jCheckBox3años.isSelected()) {
                vigencia = "3 Años";
                costo = 700; // Costo base para 3 años
            }
        } else if (jCheckBoxNo.isSelected()) {

            // Obtener la vigencia seleccionada
            if (jCheckBox1año.isSelected()) {
                vigencia = "1 Año";
                costo = 600; // Costo base para 1 año
            } else if (jCheckBox2años.isSelected()) {
                vigencia = "2 Años";
                costo = 900; // Costo base para 2 años
            } else if (jCheckBox3años.isSelected()) {
                vigencia = "3 Años";
                costo = 1100; // Costo base para 3 años
            }

        }

        if (jCheckBoxPrimeraVez.isSelected()) {

            // Obtener la información ingresada en los textboxes
            String nombre = txtNombre.getText();
            String apellidoPaterno = txtAPaterno.getText();
            String apellidoMaterno = txtAMaterno.getText();
            String fechaNacimiento = dateNacimiento.getDateStringOrEmptyString();
            String rfc = txtRFC.getText();
            String telefono = txtTelefono.getText();
            String tipoLicencia = ComboBoxTipo.getSelectedItem().toString();
            String numLicencia = lm.generarNumeroLicencia();

            // Verificar si algún campo está vacío
            if (nombre.isEmpty() || apellidoPaterno.isEmpty() || apellidoMaterno.isEmpty()
                    || fechaNacimiento.isEmpty() || rfc.isEmpty() || telefono.isEmpty() || tipoLicencia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si hay un error
            }

            // Verificar si al menos un checkbox de discapacidad está seleccionado
            if (!jCheckBoxSi.isSelected() && !jCheckBoxNo.isSelected()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una opción de discapacidad", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si no hay checkbox de discapacidad seleccionado
            }

            // Verificar que solo esté seleccionado un checkbox de vigencia
            if (!(jCheckBox1año.isSelected() ^ jCheckBox2años.isSelected() ^ jCheckBox3años.isSelected())) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una opción de vigencia", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si no se selecciona una única opción de vigencia
            }

            // Actualizar los JLabels con la información ingresada
            lblNombre.setText(nombre);
            lblApellidoPaterno.setText(apellidoPaterno);
            lblApellidoMaterno.setText(apellidoMaterno);
            lblFechaNacimiento.setText(fechaNacimiento);
            lblRFC.setText(rfc);
            lblTelefono.setText(telefono);
            lblTipo.setText(tipoLicencia);
            lblDiscapacidad.setText(discapacidadSeleccionada);
            lblVigencia.setText(vigencia);
            lblNumLicencia.setText(numLicencia);
            // Mostrar el costo en el label
            lblCosto.setText("$" + costo);

        } else if (jCheckBoxRenovacion.isSelected()) {

            String rfc = txtRFC.getText();

            String tipoLicencia = ComboBoxTipo.getSelectedItem().toString();

            // Verificar si algún campo está vacío
            if (rfc.isEmpty() || tipoLicencia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si hay un error
            }

            // Verificar si al menos un checkbox de discapacidad está seleccionado
            if (!jCheckBoxSi.isSelected() && !jCheckBoxNo.isSelected()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una opción de discapacidad", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si no hay checkbox de discapacidad seleccionado
            }

            // Verificar que solo esté seleccionado un checkbox de vigencia
            if (!(jCheckBox1año.isSelected() ^ jCheckBox2años.isSelected() ^ jCheckBox3años.isSelected())) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una opción de vigencia", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Detener la ejecución si no se selecciona una única opción de vigencia
            }

            // Actualizar los JLabels con la información ingresada
            lblRFC.setText(rfc);
            lblTipo.setText(tipoLicencia);
            lblDiscapacidad.setText(discapacidadSeleccionada);
            lblVigencia.setText(vigencia);
            // Mostrar el costo en el label
            lblCosto.setText("$" + costo);

        } else if (!jCheckBoxNo.isSelected() && !jCheckBoxSi.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de trámite", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        Inicio inicio = new Inicio();

        inicio.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
// Guardar la información en la base de datos
        String RFC = txtRFC.getText();
        String nombre = txtNombre.getText();
        String apellidoPaterno = txtAPaterno.getText();
        String apellidoMaterno = txtAMaterno.getText();
        String fechaNacimiento = dateNacimiento.getDateStringOrEmptyString();
        String telefono = txtTelefono.getText();
        int vigencia = obtenerValorVigencia();
        //double costo = Double.parseDouble(lblCosto.getText());
        String tipoLicencia = obtenerTipoLicencia();

        // Obtener el valor del JTextField y eliminar cualquier carácter no numérico
        String costoString = lblCosto.getText().replaceAll("[^\\d.]", "");

// Convertir la cadena a un número
        double costo = Double.parseDouble(costoString);
        boolean guardado = lm.generarYGuardarLicencia(RFC, nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento,
                telefono, vigencia, costo, tipoLicencia);
        if (guardado) {
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Licencia guardada correctamente.");
        } else {
            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Error al guardar la licencia. Por favor, inténtelo de nuevo.");
        }

        CurpGenerator.generarYGuardarCurp();
        //CurpGenerator.generarYGuardarCurp(nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento);
        lm.guardarPersona(RFC, nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, telefono);


    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void jCheckBoxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNoActionPerformed
        // TODO add your handling code here
        if (jCheckBoxNo.isSelected()) {
            discapacidadSeleccionada = "Ninguna";
            jCheckBoxSi.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxNoActionPerformed

    private void jCheckBoxRenovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRenovacionActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxRenovacion.isSelected()) {
            txtNombre.setEnabled(false);
            txtAPaterno.setEnabled(false);
            txtAMaterno.setEnabled(false);
            dateNacimiento.setEnabled(false);
            txtRFC.setEnabled(true);
            txtTelefono.setEnabled(false);
            ComboBoxTipo.setEnabled(true);
            jCheckBoxSi.setEnabled(true);
            jCheckBoxNo.setEnabled(true);
            jCheckBox1año.setEnabled(true);
            jCheckBox2años.setEnabled(true);
            jCheckBox3años.setEnabled(true);

            jCheckBoxPrimeraVez.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxRenovacionActionPerformed

    private void jCheckBoxSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSiActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxSi.isSelected()) {

            discapacidadSeleccionada = "Sí";
            jCheckBoxNo.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBoxSiActionPerformed

    private void jCheckBox1añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1añoActionPerformed
        // TODO add your handling code here:
        // Verificar la selección del checkbox de vigencia
        if (jCheckBox1año.isSelected()) {

            vigencia = "1 Año";
            jCheckBox2años.setSelected(false);
            jCheckBox3años.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBox1añoActionPerformed

    private void jCheckBox2añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2añosActionPerformed
        // TODO add your handling code here:

        // Verificar la selección del checkbox de vigencia
        if (jCheckBox2años.isSelected()) {
            vigencia = "2 Años";
            jCheckBox1año.setSelected(false);
            jCheckBox3años.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBox2añosActionPerformed

    private void jCheckBox3añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3añosActionPerformed
        // TODO add your handling code here:

        // Verificar la selección del checkbox de vigencia
        if (jCheckBox3años.isSelected()) {
            vigencia = "3 Años";
            jCheckBox1año.setSelected(false);
            jCheckBox2años.setSelected(false);

        }
    }//GEN-LAST:event_jCheckBox3añosActionPerformed

    private void jCheckBoxPrimeraVezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPrimeraVezActionPerformed
        // TODO add your handling code here:

        if (jCheckBoxPrimeraVez.isSelected()) {
            txtNombre.setEnabled(true);
            txtAPaterno.setEnabled(true);
            txtAMaterno.setEnabled(true);
            dateNacimiento.setEnabled(true);
            txtRFC.setEnabled(true);
            txtTelefono.setEnabled(true);
            ComboBoxTipo.setEnabled(true);
            jCheckBoxSi.setEnabled(true);
            jCheckBoxNo.setEnabled(true);
            jCheckBox1año.setEnabled(true);
            jCheckBox2años.setEnabled(true);
            jCheckBox3años.setEnabled(true);

            jCheckBoxRenovacion.setSelected(false);
        }

    }//GEN-LAST:event_jCheckBoxPrimeraVezActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupador;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerificar;
    private com.github.lgooddatepicker.components.DatePicker dateNacimiento;
    private javax.swing.JCheckBox jCheckBox1año;
    private javax.swing.JCheckBox jCheckBox2años;
    private javax.swing.JCheckBox jCheckBox3años;
    private javax.swing.JCheckBox jCheckBoxNo;
    private javax.swing.JCheckBox jCheckBoxPrimeraVez;
    private javax.swing.JCheckBox jCheckBoxRenovacion;
    private javax.swing.JCheckBox jCheckBoxSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDiscapacidad;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumLicencia;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
