/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import NEGOCIO.LicenciaManager;
import NEGOCIO.PlacaManager;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class PlacasExistentes extends javax.swing.JFrame {

    LicenciaManager lm = new LicenciaManager();
    PlacaManager pm = new PlacaManager();

    /**
     * Creates new form PlacasExistentes
     */
    public PlacasExistentes() {
        initComponents();
        this.lm = new LicenciaManager();
        this.pm = new PlacaManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupador = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        txtNumPlacas = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agrupador.setBackground(new java.awt.Color(244, 244, 244));
        Agrupador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modulo de Placas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel2)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        Agrupador.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        btnEliminar.setBackground(new java.awt.Color(0, 51, 102));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        Agrupador.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 90, 30));

        btnRegresar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        Agrupador.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 150, 40));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Ingrese su numero de licencia");
        Agrupador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel7.setText("Numero de Placas:");
        Agrupador.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel8.setText("Marca:");
        Agrupador.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel9.setText("Linea:");
        Agrupador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, -1));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel10.setText("Numero Serie:");
        Agrupador.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, -1));

        lblCosto.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lblCosto.setText("0.0");
        Agrupador.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 90, -1));
        Agrupador.add(txtNumPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 320, -1));

        txtLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenciaActionPerformed(evt);
            }
        });
        Agrupador.add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 290, -1));
        Agrupador.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 290, -1));
        Agrupador.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, -1));
        Agrupador.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 290, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche (2).png"))); // NOI18N
        Agrupador.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 230, 210));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel6.setText("Ingrese los datos del automovil");
        Agrupador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        btnGenerar.setBackground(new java.awt.Color(0, 51, 102));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        Agrupador.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 150, 40));

        btnBuscar.setBackground(new java.awt.Color(0, 51, 102));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        Agrupador.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 90, 30));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel13.setText("Licencia:");
        Agrupador.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 150, -1));

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        jLabel14.setText("Costo:");
        Agrupador.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        String placas = pm.generarYGuardarPlaca();
        

        if (placas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese datos para poder eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si hay un error

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        Inicio inicio = new Inicio();

        inicio.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:

        //tomamos los datos ingresados
        String numeroSerie = txtNumSerie.getText();
        String marca = txtMarca.getText();
        String linea = txtLinea.getText();
        String licencia = txtLicencia.getText();

        if (lm.obtenerLicenciaExistente().equals(licencia)) {
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado la licencia", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si algún campo está vacío
        if (numeroSerie.isEmpty() || marca.isEmpty() || linea.isEmpty() || licencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si hay un error
        }

        lblCosto.setText("$1000");

        JOptionPane.showMessageDialog(this, "Trámite realizado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        String placas = txtNumPlacas.getText();

        if (placas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar datos, son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si hay un error

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenciaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupador;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumPlacas;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
